import { c as createComponent, r as renderTemplate, m as maybeRenderHead, d as addAttribute, b as renderScript } from './astro/server_DWwxT_go.mjs';
import 'kleur/colors';
import 'clsx';
import { D as Data } from './case-page_af26CZR3.mjs';
/* empty css                         */

const $$FeaturedSlider = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<section class="section-y-padding border-y" data-astro-cid-xa3f7yl2> <div class="container mb-10" data-astro-cid-xa3f7yl2> <div class="flex justify-between items-center" data-astro-cid-xa3f7yl2> <h2 class="text-transparent bg-clip-text max-w-xs lg:max-w-md" style="
                    background-image: linear-gradient(
                        90deg,
                        #0b9d6c -6.7%,
                        #319ea6 36.1%,
                        #7da9ff 112.45%
                    );
                " data-astro-cid-xa3f7yl2>
Featured projects we’re proud of
</h2> <!-- pagination --> <div class="hidden lg:block" data-astro-cid-xa3f7yl2> <div class="flex items-center gap-x-3 rounded-lg" data-astro-cid-xa3f7yl2> <div class="swiper-button-prev" data-astro-cid-xa3f7yl2> <button aria-label="Previous" class="bg-body/20 aspect-square px-3 py-2 group bg-foreground/10 hover:bg-primary duration-200 ease-in-out disabled:opacity-10" data-astro-cid-xa3f7yl2> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 group-hover:text-white group-hover:-translate-x-0.5 duration-300 ease-in-out" data-astro-cid-xa3f7yl2> <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" data-astro-cid-xa3f7yl2></path> </svg></button> </div> <div class="swiper-button-next" data-astro-cid-xa3f7yl2> <button aria-label="Next" class="bg-primary aspect-square text-white px-3 py-2 group bg-accent hover:bg-primary duration-200 ease-in-out disabled:opacity-10" data-astro-cid-xa3f7yl2> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 group-hover:text-white group-hover:translate-x-0.5 duration-300 ease-in-out" data-astro-cid-xa3f7yl2> <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" data-astro-cid-xa3f7yl2></path> </svg> </button> </div> </div> </div> </div> </div> <div data-astro-cid-xa3f7yl2> <div class="swiper featured-slider overflow-visible cursor-ew-resize" data-astro-cid-xa3f7yl2> <div class="swiper-wrapper" data-astro-cid-xa3f7yl2> ${Data.case_studies.map((item) => renderTemplate`<div class="swiper-slide max-w-[calc(100%-40px)] sm:max-w-md lg:max-w-[440px] h-fit" data-astro-cid-xa3f7yl2> <a class="group"${addAttribute(item.case_url, "href")} data-astro-cid-xa3f7yl2> <div class="w-full mb-5 aspect-[17/9]" data-astro-cid-xa3f7yl2> <img class="w-full h-full object-cover"${addAttribute(item.case_img, "src")}${addAttribute(item.title, "alt")} loading="lazy" data-astro-cid-xa3f7yl2> </div> <p class="text-3xl mb-3 font-normal max-w-md" data-astro-cid-xa3f7yl2> ${item.title} </p> <div class="flex items-center text-sm text-primaryg gap-x-2" data-astro-cid-xa3f7yl2> <p class="uppercase text-primary font-semibold" data-astro-cid-xa3f7yl2>
Read study
</p> <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg" data-astro-cid-xa3f7yl2> <rect width="17" height="17" fill="url(#paint0_linear_27_769)" data-astro-cid-xa3f7yl2></rect> <path d="M5.72681 11.6314L11.6477 5.71045" stroke="#F3EFE5" stroke-width="0.944444" stroke-linecap="round" stroke-linejoin="round" data-astro-cid-xa3f7yl2></path> <path d="M11.8872 11.0935V5.59107" stroke="#F3EFE5" stroke-width="0.944444" stroke-linecap="round" stroke-linejoin="round" data-astro-cid-xa3f7yl2></path> <path d="M5.66673 5.47097H11.8865" stroke="#F3EFE5" stroke-width="0.944444" stroke-linecap="round" stroke-linejoin="round" data-astro-cid-xa3f7yl2></path> <defs data-astro-cid-xa3f7yl2> <linearGradient id="paint0_linear_27_769" x1="8.5" y1="2.59722" x2="25.9722" y2="22.4306" gradientUnits="userSpaceOnUse" data-astro-cid-xa3f7yl2> <stop stop-color="#1F9BA4" data-astro-cid-xa3f7yl2></stop> <stop offset="1" stop-color="#4744DE" data-astro-cid-xa3f7yl2></stop> </linearGradient> </defs> </svg> </div> </a> </div>`)} </div> </div> <div class="flex items-center lg:hidden container mt-8 justify-start gap-4" data-astro-cid-xa3f7yl2> <div class="swiper-button-prev" data-astro-cid-xa3f7yl2> <button aria-label="Previous" class="bg-body/20 aspect-square px-3 py-2 group bg-foreground/10 hover:bg-primary duration-200 ease-in-out disabled:opacity-10" data-astro-cid-xa3f7yl2> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 group-hover:text-white group-hover:-translate-x-0.5 duration-300 ease-in-out" data-astro-cid-xa3f7yl2> <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" data-astro-cid-xa3f7yl2></path> </svg></button> </div> <div class="swiper-button-next" data-astro-cid-xa3f7yl2> <button aria-label="Next" class="bg-primary aspect-square text-white px-3 py-2 group bg-accent hover:bg-primary duration-200 ease-in-out disabled:opacity-10" data-astro-cid-xa3f7yl2> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 group-hover:text-white group-hover:translate-x-0.5 duration-300 ease-in-out" data-astro-cid-xa3f7yl2> <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" data-astro-cid-xa3f7yl2></path> </svg> </button> </div> </div> </div> ${renderScript($$result, "D:/MYWork/astroStart/regular-resonance/src/components/FeaturedSlider.astro?astro&type=script&index=0&lang.ts")}  </section>`;
}, "D:/MYWork/astroStart/regular-resonance/src/components/FeaturedSlider.astro", undefined);

export { $$FeaturedSlider as $ };
